cat <<EOF > clusterip.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
    app: nginx-app
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
EOF
kubectl apply -f clusterip.yaml
