cat <<EOF > loadbalancer_internal_ip.yaml
kind: Service
apiVersion: v1
metadata:
  name: lb-internal-ip
  namespace: default
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
EOF
kubectl apply -f loadbalancer_internal_ip.yaml
