cat <<EOF > loadbalancer.yaml
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalanced-service
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
EOF
kubectl apply -f loadbalancer.yaml
