cat <<EOF > nodeport.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30001
    protocol: TCP
EOF
kubectl apply -f nodeport.yaml
