# storage1.yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: block-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    kubernetes.io/description: "Use Sky TV block storage as default storage backend"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/cinder
reclaimPolicy: Delete
parameters:
  type: b1.standard
  availability: nz-hlz-1a
  fstype: ext4
