heat_template_version: 2016-10-14

description: |
  The heat template is used to create a server as a load balancer member.
parameters:
  keypair:
    type: string
    default: security-key
  image_id:
    type: string
    default: 102172df-9872-47df-b66b-2bcecb3a74b7
  flavor_id:
    type: string
    default: c1.c1r1
  network_id:
    type: string
    default: 550677db-0232-418b-aeb5-f461cf907967
  sg_ids:
    type: comma_delimited_list
  public_network:
    type: string
  pool_id:
    type: string
    default: no_default
    hidden: true
  metadata:
    type: json

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: flavor_id }
      networks:
        - network: {get_param: network_id}
      key_name: {get_param: keypair}
      security_groups: {get_param: sg_ids}
      metadata: {get_param: metadata}
      config_drive: true
      user_data_format: RAW
      user_data: |
          #!/bin/sh
          MYIP=$(/sbin/ifconfig ens3 | grep 'inet '| awk '{print $2}');
          OUTPUT="Welcome to my $MYIP";
<<<<<<< HEAD
          while true; do echo "HTTP/1.1 200 OK\r\n\r\n${OUTPUT}\r" | sudo nc -l -p 80; done
=======
          while true; do echo -e "HTTP/1.1 200 OK\r\n\r\n${OUTPUT}\r" | sudo nc -l -p 80; done
>>>>>>> 1c3f285505f8f8606984d3c1d13d6552f8b029c0
  pool_member:
    type: OS::Octavia::PoolMember
    properties:
      address: {get_attr: [server, first_address]}
      pool: {get_param: pool_id}
      protocol_port: 80
  server_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_network}
      port_id: {get_attr: [server, addresses, {get_param: network_id}, 0, port]}

outputs:
  server_id:
    value: {get_resource: server}
