#
# HOT template for creating a new database instance
#

heat_template_version: 2015-04-30

parameters:

  instance_name:
    type: string
    description: The name of your database instance
    default: <INSTANCE NAME>

  flavor:
    type: string
    description: Flavour for the database instance
    default: <FLAVOR ID>
    constraints:
      - custom_constraint: nova.flavor

  datastore:
    type: string
    description: The type of datastore we are going to use. (In this case mysql)
    default: mysql

  datastore_version:
    type: string
    description: The version number of mysql
    default: 5.7.29

  network:
    type: string
    description: The network your instance will be attached to
    default: <NETWORK ID>

  size:
    type: string
    description: The size of your database instance in GB. For this example we'll use 5 GB
    default: 5

resources:
  database:
    type: OS::Trove::Instance
    properties:
      flavor: { get_param: flavor }
      databases: [{name: DB-1}] # You can change the name of your database, or add multiple databases here
      datastore_type: { get_param: datastore }
      datastore_version: { get_param: datastore_version }
      name: { get_param: instance_name }
      networks: [network: { get_param: network }]
      size: { get_param: size }
      users: [{name: db_user_1, password: db_pass, databases: [DB-1]}] # You can change the database user information here.
